apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  clusterIP: None  # This ensures that the StatefulSet pods get a stable network identity
  ports:
  - port: 3306
  selector:
    app: mysql
